<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <PackageProjectUrl>https://github.com/dosymep/dosymep.Autodesk.dosymep.Revit.ServerClient</PackageProjectUrl>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="System.Net.Http"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json">
            <PrivateAssets>all</PrivateAssets>
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>
</Project>
